#cloud-config
# See the autoinstall documentation at:
# https://canonical-subiquity.readthedocs-hosted.com/en/latest/reference/autoinstall-reference.html
autoinstall:
  version: 1
  interactive-sections:
    - identity
  active-directory:
    admin-name: ""
    domain-name: anx.local
  apt:
    disable_components: []
    fallback: offline-install
    geoip: true
    mirror-selection:
      primary:
        - country-mirror
        - arches: &id001
            - amd64
            - i386
          uri: http://archive.ubuntu.com/ubuntu/
        - arches: &id002
            - s390x
            - arm64
            - armhf
            - powerpc
            - ppc64el
            - riscv64
          uri: http://ports.ubuntu.com/ubuntu-ports
    preserve_sources_list: false
    security:
      - arches: *id001
        uri: http://security.ubuntu.com/ubuntu/
      - arches: *id002
        uri: http://ports.ubuntu.com/ubuntu-ports
  packages:
    - git
    - ansible
  codecs:
    install: true
  drivers:
    install: true
  identity:
    hostname: CHANGEME
    password: $y$j9T$pV3LjPDUvbBhu7JW2xMBI0$ik/pcSSfpQDTERptcbV1pqWUUzoBh7Ucb6BJzOXXAu/
    realname: CHANGE ME
    username: changeme
  keyboard:
    layout: at
    toggle: null
    variant: nodeadkeys
  locale: de_AT.UTF-8
  oem:
    install: true
  shutdown: poweroff
  source:
    id: ubuntu-desktop
    search_drivers: true
  ssh:
    allow-pw: false
    authorized-keys: []
    install-server: false
  storage:
    config:
      - id: nvme-controller-nvme0
        type: nvme_controller
        transport: pcie
        preserve: true
      - id: disk-nvme0n1
        type: disk
        path: /dev/nvme0n1
        nvme_controller: nvme-controller-nvme0
        ptable: gpt
        wipe: superblock-recursive
        preserve: false
        grub_device: false
      - id: efipart
        type: partition
        device: disk-nvme0n1
        offset: 1048576
        size: 1127219200
        flag: boot
        grub_device: true
      - id: bootpart
        type: partition
        device: disk-nvme0n1
        size: 2147483648
      - id: pvpart
        type: partition
        device: disk-nvme0n1
        size: -1
      - id: dm_crypt-0
        type: dm_crypt
        volume: pvpart
        key: tempkey
      - id: vg0
        type: lvm_volgroup
        name: vg0
        devices:
          - dm_crypt-0
      - id: root_lv
        type: lvm_partition
        name: root_lv
        volgroup: vg0
        size: 45G
      - id: home_lv
        type: lvm_partition
        name: home_lv
        volgroup: vg0
        size: -1
      - id: efipart_fs
        type: format
        volume: efipart
        fstype: fat32
      - id: bootpart_fs
        type: format
        volume: bootpart
        fstype: ext4
      - id: root_lv_fs
        type: format
        volume: root_lv
        fstype: ext4
      - id: home_lv_fs
        type: format
        volume: home_lv
        fstype: ext4
      - id: efipart_mount
        type: mount
        device: efipart_fs
        path: /boot/efi
      - id: bootpart_mount
        type: mount
        device: bootpart_fs
        path: /boot
      - id: root_lv_mount
        type: mount
        device: root_lv_fs
        path: /
      - id: home_lv_mount
        type: mount
        device: home_lv_fs
        path: /home
  timezone: Europe/Vienna
  updates: all
  late-commands:
    - curtin in-target -- apt-get update
    - curtin in-target -- apt-get install -y curl vim tpm2-tools
    - curtin in-target -- curl -o /tmp/tpm2-keysetup.sh https://raw.githubusercontent.com/greflm13/ubuntu-setup/refs/heads/main/tpm2-keysetup.sh
    - curtin in-target -- curl -o /tmp/3rd-party-software.sh https://raw.githubusercontent.com/greflm13/ubuntu-setup/refs/heads/main/3rd-party-software.sh
    - curtin in-target -- /bin/bash /tmp/tpm2-keysetup.sh
    - curtin in-target -- /bin/bash /tmp/3rd-party-software.sh
  user-data:
    packages:
      - ansible
      - git
    package_update: true
    package_upgrade: true
    ansible:
      install_method: distro
      pull:
        url: "https://github.com/greflm13/ubuntu-setup.git"
        playbook_name: ansible-setup.yml
